#! /bin/sh

set -ex

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

[ -f freestanding-toolchain ] || ( curl -Lo freestanding-toolchain https://github.com/mintsuki/freestanding-toolchain/raw/trunk/freestanding-toolchain && chmod +x freestanding-toolchain )
[ -d freestanding-headers ] || git clone https://github.com/mintsuki/freestanding-headers.git --depth=1
[ -d libgcc-binaries ] || git clone https://github.com/mintsuki/libgcc-binaries.git --depth=1
[ -f limine.h ] || curl -Lo limine.h https://github.com/limine-bootloader/limine/raw/trunk/limine.h
[ -d flanterm ] || git clone https://github.com/mintsuki/flanterm.git --depth=1
if ! [ -d printf ]; then
    mkdir printf
    curl -Lo printf/printf.c https://github.com/eyalroz/printf/raw/master/src/printf/printf.c
    curl -Lo printf/printf.h https://github.com/eyalroz/printf/raw/master/src/printf/printf.h
fi

MLIBC_VERSION=bfcdb855c1cff1f31dfa8deea1a395fdea79cb34

if ! [ -d mlibc-headers ]; then
    curl -Lo mlibc.tar.gz https://github.com/managarm/mlibc/archive/${MLIBC_VERSION}.tar.gz
    tar -xf mlibc.tar.gz
    mkdir mlibc-build
    cd mlibc-build
    meson setup \
        --cross-file ../cross_file.txt \
        --prefix=/ \
        -Dheaders_only=true \
        -Ddisable_crypt_option=true \
        -Ddisable_iconv_option=true \
        -Ddisable_intl_option=true \
        ../mlibc-${MLIBC_VERSION}
    ninja
    mkdir ../mlibc-headers-out
    DESTDIR="$(cd ../mlibc-headers-out && pwd -P)" ninja install
    cd ..
    mv mlibc-headers-out/include mlibc-headers
    rm -rf mlibc.tar.gz mlibc-${MLIBC_VERSION} mlibc-build mlibc-headers-out
fi

mkdir -p build-aux
cp "$(automake --print-libdir)/install-sh" build-aux

autoreconf -fvi -Wall
